FILTER_FIRSTNAME = "Sally"
FILTER_LASTNAME = "Brown"
FILTER_CHECKIN = "2013-02-21"
FILTER_CHECKOUT = "2014-10-24"

CREATED_FIRSTNAME = "Jim"
CREATED_LASTNAME = "Boil"
CREATED_TOTALPRICE = 113
CREATED_DEPOSITPAID = False
CREATED_CHECKIN = "2018-01-01"
CREATED_CHECKOUT = "2019-01-01"
CREATED_ADDITIONALNEEDS = "Dinner"



UPDATED_FIRSTNAME = "Arthur"
UPDATED_LASTNAME = "Morgan"
UPDATED_TOTALPRICE = 116
UPDATED_DEPOSITPAID = True
UPDATED_CHECKIN = "2018-03-01"
UPDATED_CHECKOUT = "2019-07-01"
UPDATED_ADDITIONALNEEDS = "Breakfast"


NEW_FIRSTNAME = "Megan"
NEW_LASTNAME = "Hicks"


